parameters:
    smile.page_view.twig_extension.class: Smile\Bundle\SimplePageViewBundle\Twig\Extension\PageViewExtension
    smile.page_view.manager.class: Smile\Bundle\SimplePageViewBundle\Manager\PageViewManager
    smile.page_view.aggregate_data_command.class: Smile\Bundle\SimplePageViewBundle\Command\PageViewDataAggregateCommand
    smile.page_view.logger.class: Symfony\Bridge\Monolog\Logger
    smile.page_view.logger_handler.class: Monolog\Handler\StreamHandler

services:
    smile.page_view.manager:
        class: %smile.page_view.manager.class%
        arguments: [@doctrine.orm.entity_manager]

    smile.page_view.twig_extension:
        class: %smile.page_view.twig_extension.class%
        arguments: [@router]
        tags:
            - { name: twig.extension }

    smile.page_view.aggregate_data_command:
        class: %smile.page_view.aggregate_data_command.class%
        arguments: [@smile.page_view.manager, @smile.page_view.logger]
        tags:
            - { name: console.command }

    smile.page_view.logger:
        class: %smile.page_view.logger.class%
        arguments: ['page_view']
        calls:
            - [pushHandler, [@smile.page_view.logger_handler]]

    smile.page_view.logger_handler:
        class: %smile.page_view.logger_handler.class%
        arguments: [%kernel.logs_dir%/%kernel.environment%.page_view.log, 200]